/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/credits`; params?: Router.UnknownInputParams; } | { pathname: `/guide`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/results`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/decks` | `/decks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rank` | `/rank`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/multiplayer/host`; params?: Router.UnknownInputParams; } | { pathname: `/multiplayer`; params?: Router.UnknownInputParams; } | { pathname: `/multiplayer/join`; params?: Router.UnknownInputParams; } | { pathname: `/multiplayer/lobby`; params?: Router.UnknownInputParams; } | { pathname: `/singleplayer/dailydeck`; params?: Router.UnknownInputParams; } | { pathname: `/singleplayer`; params?: Router.UnknownInputParams; } | { pathname: `/singleplayer/quickplay`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/credits`; params?: Router.UnknownOutputParams; } | { pathname: `/guide`; params?: Router.UnknownOutputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/results`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/decks` | `/decks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rank` | `/rank`; params?: Router.UnknownOutputParams; } | { pathname: `/game`; params?: Router.UnknownOutputParams; } | { pathname: `/multiplayer/host`; params?: Router.UnknownOutputParams; } | { pathname: `/multiplayer`; params?: Router.UnknownOutputParams; } | { pathname: `/multiplayer/join`; params?: Router.UnknownOutputParams; } | { pathname: `/multiplayer/lobby`; params?: Router.UnknownOutputParams; } | { pathname: `/singleplayer/dailydeck`; params?: Router.UnknownOutputParams; } | { pathname: `/singleplayer`; params?: Router.UnknownOutputParams; } | { pathname: `/singleplayer/quickplay`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/credits${`?${string}` | `#${string}` | ''}` | `/guide${`?${string}` | `#${string}` | ''}` | `/leaderboard${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/decks${`?${string}` | `#${string}` | ''}` | `/decks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/games${`?${string}` | `#${string}` | ''}` | `/games${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rank${`?${string}` | `#${string}` | ''}` | `/rank${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `/multiplayer/host${`?${string}` | `#${string}` | ''}` | `/multiplayer${`?${string}` | `#${string}` | ''}` | `/multiplayer/join${`?${string}` | `#${string}` | ''}` | `/multiplayer/lobby${`?${string}` | `#${string}` | ''}` | `/singleplayer/dailydeck${`?${string}` | `#${string}` | ''}` | `/singleplayer${`?${string}` | `#${string}` | ''}` | `/singleplayer/quickplay${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/credits`; params?: Router.UnknownInputParams; } | { pathname: `/guide`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/results`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/decks` | `/decks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rank` | `/rank`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/multiplayer/host`; params?: Router.UnknownInputParams; } | { pathname: `/multiplayer`; params?: Router.UnknownInputParams; } | { pathname: `/multiplayer/join`; params?: Router.UnknownInputParams; } | { pathname: `/multiplayer/lobby`; params?: Router.UnknownInputParams; } | { pathname: `/singleplayer/dailydeck`; params?: Router.UnknownInputParams; } | { pathname: `/singleplayer`; params?: Router.UnknownInputParams; } | { pathname: `/singleplayer/quickplay`; params?: Router.UnknownInputParams; };
    }
  }
}
